language: go

sudo: false

go:
  - 1.11.x

services:
  - postgresql

before-script:
  - psql -a -c "CREATE DATABASE webauthn;" -U postgres
  - psql -a -c "CREATE USER testuser WITH PASSWORD 'testpwd';" -U postgres
  - psql -a -d "webauthn" -f ./createtables.sql -U testuser
  - export DB_CONNSTRING="user=testuser password=testpwd host=localhost dbname=webauthn sslmode=disable"

script:
  - env GO111MODULE=on go test -coverprofile=coverage.txt -covermode=count ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)  
