language: go

go:
  - 1.12.x

services:
  - postgresql

env:  
  - GO111MODULE=on DB_CONNSTRING="user=testuser password=testpwd host=localhost dbname=webauthn sslmode=disable"  
  
before_script:
  - psql -a -c "CREATE DATABASE webauthn;" -U postgres
  - psql -a -c "CREATE USER testuser WITH PASSWORD 'testpwd';" -U postgres
  - psql -a -d "webauthn" -f ./db/createtables.sql -U testuser

script:
  - go test -coverprofile=coverage.txt -covermode=count ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)  
