version: "3"
services:
  cache:
    image: redis:alpine
    volumes:
      - ${CACHE_DATA_DIR}:/data
    command: redis-server --appendonly yes
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./db/createtables.sql:/docker-entrypoint-initdb.d/createtables.sql
      - ${DB_DATA_DIR}:/var/lib/postgresql/data
  web:
    build: .
    restart: on-failure
    ports:
      - 8443:8443
    environment:
      DB_CONNSTRING: "dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} host=db sslmode=disable"
      REDIS_ADDR: cache:6379
      REDIS_NETWORK: tcp
      REDIS_PWD:
      SESSION_KEY:
    volumes:
      - ${CERTS_DIR}:/opt/webauthn/certs 
      - ./config.json:/opt/webauthn/config/config.json
    depends_on:
      - db
      - cache
    command: "-config=./config/config.json -cert=./certs/cert.pem -key=./certs/key.pem"